name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2

      - name: Verify formatting and lint
        if: matrix.os == 'ubuntu-latest'
        run: |
          deno fmt --check
          deno lint

      - name: Install & run pagefind
        run: |
          deno run -A demos/pagefind.ts
          deno run -A demos/pagefind.ts

      - name: Install & run tailwind
        run: |
          deno run -A demos/tailwind.ts
          deno run -A demos/tailwind.ts
